### PR TITLE
Organize data constructors and accessors hierarchically

### PR DESCRIPTION
**Pull request by lyokha**
This also fixes issue #41 

This patch makes my tagbar look like

hasktags-data-nested

It supports GADTs too.

For this I used following settings in my `.vimrc`:

```vim
let g:tagbar_type_haskell = {
    \ 'ctagsbin'  : 'hasktags',
    \ 'ctagsargs' : '-x -c -o-',
    \ 'kinds'     : [
        \  'm:modules:0:1',
        \  'd:data:0:1',
        \  'd_gadt:data gadt:0:1',
        \  't:type names:0:1',
        \  'nt:newtype:0:1',
        \  'c:classes:0:1',
        \  'cons:constructors:1:1',
        \  'c_gadt:constructor gadt:1:1',
        \  'c_a:constructor accessors:1:1',
        \  'ft:function types:1:1',
        \  'fi:function implementations:0:1',
        \  'o:others:0:1'
    \ ],
    \ 'sro'        : '.',
    \ 'kind2scope' : {
        \ 'm'      : 'module',
        \ 'c'      : 'class',
        \ 'd'      : 'data',
        \ 'd_gadt' : 'd_gadt',
        \ 'c_gadt' : 'c_gadt',
        \ 'nt'     : 'newtype',
        \ 'cons'   : 'cons',
        \ 'c_a'    : 'accessor'
    \ },
    \ 'scope2kind'  : {
        \ 'module'  : 'm',
        \ 'class'   : 'c',
        \ 'data'    : 'd',
        \ 'newtype' : 'nt',
        \ 'cons'    : 'c_a',
        \ 'd_gadt'  : 'c_gadt'
    \ }
\ }
```

__P.S.__ I found similar solution (PR #13) after I already implemented this.

### CODE REVIEW

**Comment by lyokha** [comment]
Figured out that it does not break *etags* and *not-extended* *ctags* modes because *kinds* (those elements that now additionally contain hierarchies in ctags *format=2*) are only printed in *extended* *ctags* mode.

**Comment by jhenahan** [comment]
Nice! I'll merge this in and make a release along with adding your config to the README. Thanks a lot!

**Comment by lyokha** [comment]
Below is a couple of tagbar views after all the changes (using *JuicyPixels* source code). Notice that all operator-like functions are correctly displayed, functions have prototypes, and classes and instances have own scopes.

hasktags-jp-1
hasktags-jp-2

**Comment by lyokha** [comment]
Yes, so far it works fine for me. I checked this with my own source codes and source codes from library JuicyPixels. It still does not support *type families*, but at least it shows them without messing up the screen. It also would be nice to add tags for *foreign* declarations. But not now.

P.S. I do not know how to *squash* commits. What do you mean by this?

**Comment by jhenahan** [comment]
You should be able to do something like

    git rebase -i 16c90b9^

This will open an editor session with a list of your commits with the word `pick` in front of them. Change all those `pick`s to `squash` except for the line with `Organize data constructors and accessors hierarchically`. Then `ZZ` or `:wq`, and it should open a standard commit message editor session containing the original commit as the title, and all the other commits as notes. You should then end up with a single commit containing all your changes. Then `git push --force` to overwrite your remote and it should update here so I can merge it as a single commit.

I'll work on some contributing guidelines with a version of those instructions after I get your changes merged.

**Comment by lyokha** [comment]
Thank you for this help! I never knew about squashing commits! Done.

Here is my latest *.vimrc* settings:

```vim
let g:tagbar_type_haskell = {
    \ 'ctagsbin'    : 'hasktags',
    \ 'ctagsargs'   : '-x -c -o-',
    \ 'kinds'       : [
        \  'm:modules:0:1',
        \  'd:data:0:1',
        \  'd_gadt:data gadt:0:1',
        \  'nt:newtype:0:1',
        \  'c:classes:0:1',
        \  'i:instances:0:1',
        \  'cons:constructors:0:1',
        \  'c_gadt:constructor gadt:0:1',
        \  'c_a:constructor accessors:1:1',
        \  't:type names:0:1',
        \  'pt:pattern types:0:1',
        \  'pi:pattern implementations:0:1',
        \  'ft:function types:0:1',
        \  'fi:function implementations:0:1',
        \  'o:others:0:1'
    \ ],
    \ 'sro'          : '.',
    \ 'kind2scope'   : {
        \ 'm'        : 'module',
        \ 'd'        : 'data',
        \ 'd_gadt'   : 'd_gadt',
        \ 'c_gadt'   : 'c_gadt',
        \ 'nt'       : 'newtype',
        \ 'cons'     : 'cons',
        \ 'c_a'      : 'accessor',
        \ 'c'        : 'class',
        \ 'i'        : 'instance'
    \ },
    \ 'scope2kind'   : {
        \ 'module'   : 'm',
        \ 'data'     : 'd',
        \ 'newtype'  : 'nt',
        \ 'cons'     : 'c_a',
        \ 'd_gadt'   : 'c_gadt',
        \ 'class'    : 'ft',
        \ 'instance' : 'ft'
    \ }
\ }
```

**Pull request merged**
